---

- name: disable IPv6
  sysctl:
    name={{ item }}
    value=1
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  with_items:
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.default.disable_ipv6"
    - "net.ipv6.conf.lo.disable_ipv6"
  when: ipv6 is not defined or ipv6.disable == 'True'
  tags:
    - ipv6


- name: enable IPv6
  sysctl:
    name={{ item }}
    value=0
    state=present
    sysctl_file=/etc/sysctl.conf
    reload=yes
  with_items:
    - "net.ipv6.conf.all.disable_ipv6"
    - "net.ipv6.conf.default.disable_ipv6"
    - "net.ipv6.conf.lo.disable_ipv6"
  when: ipv6 is defined and ipv6.disable == 'False'
  tags:
    - ipv6
