---

- name: prepare packages
  package:
    name={{item}}
    state=present
  with_items:
   - elasticsearch
  register: apt_res
  retries: 5
  until: apt_res is success
  tags: elasticsearch

- name: set elasticsearch configuration
  template:
   src: "elasticsearch.yml.j2"
   dest: "/etc/elasticsearch/elasticsearch.yml"
   backup: yes
  tags: elasticsearch

- name: enable elasticsearch on boot
  service:
    name="elasticsearch"
    enabled=yes
    state=started
  tags: elasticsearch

