---

  - name: prep os for more open files
    lineinfile:
      line="{{ item }}"
      dest=/etc/security/limits.conf
    with_items:
      - "ubuntu soft nofile 65535"
      - "ubuntu hard nofile 65535"
    tags: redis

  - name: prep os for more tcp backlog
    sysctl:
      name=net.core.somaxconn
      value=512
      state=present
    tags:
      - redis

  - name: install packages
    package:
      name="{{ item }}"
      state=present
    with_items:
      - redis-sentinel
      - redis-tools
    register: aptredis
    retries: 5
    until: aptredis is success
    tags: redis

  - name: set haredis haproxy notification script
    copy:
     src="notification.sh"
     dest="/var/lib/redis/notification.sh"
     owner=redis
     group=redis
     mode=0755
    notify:
      - restart redis-sentinel
    tags: redis

  - name: set redis default configuration file
    copy:
     src="redis-default.conf"
     dest="/etc/default/redis-server"
    notify:
      - restart redis-sentinel
    when: aptredis.changed
    tags: redis

  - name: set redis-sentinel initial configuration file
    template:
      src="redis-sentinel.conf.j2"
      dest="{{item}}"
    notify:
      - restart redis-sentinel
    when: aptredis.changed
    with_items:
      - "/etc/redis/sentinel.conf"
    tags: redis

  - name: enable redis-sentinel service on boot
    service:
      name="redis-sentinel"
      enabled=yes
    when: aptredis.changed
    tags: redis
