---

- name: install ntp packages
  package:
    name=ntp
    state=present
  register: ntp_install
  tags: ntp

- name: Set ntp clock sync
  command: ntpd -gq
  when: ntp_install is changed
  ignore_errors: yes
  failed_when: False
  tags: ntp

- name: ensure ntp is running | Debian
  service:
    name=ntp
    state=started
  tags: ntp
  when: ansible_os_family == 'Debian'

- name: ensure ntpd is running | RedHat
  service:
    name=ntpd
    state=started
  tags:
    - ntp
  when: ansible_os_family == 'RedHat'

